title: nxhelp
baseURL: /
params:
  description: A minimal blogging theme for Stackbit
  palette: blue
  header:
    type: header
    template: header
    title: nxhelp
    tagline: by Thomas Uhde
    has_nav: true
    nav_links:
      - type: action
        template: action
        label: Home
        url: /
        style: link
      - type: action
        template: action
        label: About
        url: /about
        style: link
      - type: action
        template: action
        label: Contact
        url: /contact
        style: link
    has_social: true
    social_links:
      - type: action
        template: action
        label: Twitter
        url: 'https://twitter.com/ThomasUhde'
        style: icon
        icon_class: fa-twitter
        new_window: true
      - type: action
        template: action
        label: GitHub
        url: 'https://github.com/acidix'
        style: icon
        icon_class: fa-github
        new_window: true
      - type: action
        template: action
        label: LinkedIn
        url: 'https://www.linkedin.com/in/ThomasUhde'
        style: icon
        icon_class: fa-linkedin
        new_window: true
  footer:
    type: footer
    template: footer
    content: >-
      &copy; Stackbit. All rights reserved. This Jamstack site was created on <a
      href="https://www.stackbit.com" target="_blank"
      rel="noopener">Stackbit</a>. Get yours <a
      href="https://app.stackbit.com/create?theme=fjord" target="_blank"
      rel="noopener">here</a>.
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
